### ISSUE TITLE
progress HLS-VI

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#103]
## Summary

progress HLS-VI

### Acceptance Criteria:

```[tasklist]
- [ ] Finalize and sign the HLS-VI project plan
- [ ] Finalize and sign the HLS-VI F2I DG Memo
- [X] Develop documentation and ORR artifacts, extent tbd 
- [X] Establish a review board. 
```
# Dependencies
Review board establishment: ESDIS and DAAC coordination

# Risks
None currently identified

# Future PI
Operational Readiness Review (ORR): ~~notionally May 1, 2024~~

**Comment by CherrelleTucker** [comment]
@jenny-m-wood can you drop a link to the artifacts here?

**Comment by jenny-m-wood** [comment]
ORR artifacts:

- [ORR Slide Template](https://drive.google.com/drive/folders/1eFJqfwzCgBcA6Jr6FogqWd2E-Z4Nms0X)
- [ORR Decision Memo Template](https://docs.google.com/document/d/1YvuDiCZ3TDN44ek0ezNHTxkmG__FK5EcHZe8l91KGdQ/edit#heading=h.hrp6lrbkvzit)
