### ISSUE TITLE
Update Program Plan to prepare for release next quarter. 

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#109]
### Acceptance Criteria:
```[tasklist]
- [x] Replace “Gerald” with “Program Scientist” and refer to Natasha
- [ ] Begin approval process by end of PI.
- [ ] Document necessary changes as SNWG moves to Earth Action
```
# Dependencies
None currently identified

# Risks
None currently identified

# Future PI
Information Management Plan

**Comment by CherrelleTucker** [comment]
[2024-08-26 SNWG MO Internal Planning Meeting](https://docs.google.com/document/d/1YQjZuNkYhqCuSQutUDnp6ialVxCABeLUBDHDRPuOt7g/edit)
- [Program Plan Updates Working List](https://docs.google.com/spreadsheets/d/1nv_u0Lpl-yC1helPmX_wIBAANcOg6ACjg8tIxcXTJpA/edit?gid=0#gid=0) - JW highlighted items to discuss w/ Sean and Eric

**Comment by CherrelleTucker** [comment]
@jenny-m-wood are any of these ready to mark off?

**Comment by jenny-m-wood** [comment]
@CherrelleTucker maybe the first one? The others are still in progress.
