### ISSUE TITLE
Support the initial interview process for Assessment 2024

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#110]
## Summary
Support the initial interview process for Assessment 2024

### Acceptance Criteria:

```[tasklist]
- [x] Cherrelle assist with workshops
- [ ] gearing up with Cost estimations next spring
```
# Dependencies
None currently identified

# Risks
None currently identified

# Future PI

**Comment by CherrelleTucker** [comment]
@kvirts has "gearing up with Cost estimations next spring" been started/completed/gathered any relevant documentation?

**Comment by kvirts** [comment]
I'm not sure.  I believe that is Sean's responsibility.

**Comment by CherrelleTucker** [comment]
@Spgregwork has "gearing up with Cost estimations next spring" been started/completed/gathered any relevant documentation?
